Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,26 +1,56 @@
-name: Build And Publish Go-KAS Docker image
-
+name: Build and Publish
+env:
+  CONTAINER_ARCHS: linux/amd64,linux/arm64
 on:
   push:
     branches:
       - PLAT-2416-kas-replace-python-go
+      - main
   pull_request:
-    branches:
-      - PLAT-2416-kas-replace-python-go
+    types:
+      - opened
+      - synchronize
+      - reopened
   release:
-    types: [published]
-
+    types:
+      - published
 jobs:
-  build-and-test:
+  version:
+    runs-on: ubuntu-latest
+    env:
+      RELEASE_TAG: "${{ github.event.release.tag_name}}"
+    outputs:
+      VERSION: "${{ steps.info.outputs.VERSION }}"
+      SHA_TAG: "${{ steps.info.outputs.SHA }}"
+      SERVER_TARGET: "${{ github.event_name == 'release' && 'server' || 'server-debug' }}"
+    timeout-minutes: 5
+    steps:
+      - uses: actions/checkout@v3
+      - name: Validate releases are on main (reviewed) branch
+        if: github.event_name == 'release'
+        run: |
+          git fetch origin main:main
+          git fetch --all --tags --force
+          if ! git merge-base --is-ancestor "$RELEASE_TAG" main; then
+            echo "# Invalid release tag [$RELEASE_TAG] - must be on `main` branch" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+      - run: |-
+          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
+          echo "SHA=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+        id: info
+
+  ci:
+    needs:
+      - version
+    permissions:
+      packages: ${{ github.ref == 'refs/heads/main' && github.event_name == 'release' && "write" || "read" }}
+      contents: read
     runs-on: ubuntu-latest
     timeout-minutes: 30
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-      - name: Extract version
-        run: |
-          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
-        id: info
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
       - name: Set up Docker Buildx
@@ -29,38 +59,22 @@ jobs:
         uses: docker/build-push-action@v4
         with:
           context: .
-          platforms: linux/amd64
+          platforms: "${{ env.CONTAINER_ARCHS }}"
           push: false
           target: tester
-  build-and-push:
-    if: github.ref != 'refs/heads/main'
-    runs-on: ubuntu-latest
-    permissions:
-      packages: write
-      contents: read
-    timeout-minutes: 30
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Extract version
-        run: |
-          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
-        id: info
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
       - name: Login to GitHub Container Registry
+        if: github.ref == 'refs/heads/main' && github.event_name == 'release'
         uses: docker/login-action@v2
         with:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
       - name: Build and push
+        if: github.ref == 'refs/heads/main' && github.event_name == 'release'
         uses: docker/build-push-action@v4
         with:
           context: .
-          platforms: linux/amd64,linux/arm64
-          target: server-debug
+          platforms: "${{ env.CONTAINER_ARCHS }}"
           push: true
-          tags: ghcr.io/opentdf/gokas:${{ env.VERSION }}
+          tags: ghcr.io/opentdf/gokas:${{ version.outputs.VERSION }}
+
